config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "static_pages#home"
    resources :users do
      get "cart", to: "carts#show"
    end
    resources :contacts
    resources :shops
    resources :products
    resources :line_items, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  
  validates :email, presence: true, length: { maximum: 255 },format: { with: VALID_EMAIL_REGEX },uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true, on: :edit
  
  has_one :cart
  has_one :shop
	has_many :contacts
  has_many :vouchers, through: :user_voucher

  after_create :check_cart
  after_create :check_shop1

  private

  def check_shop1
    create_shop unless shop
  end

  def check_cart
    byebug
    create_cart unless cart
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	end

	def show
	end

	def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      flash[:danger] = "You do not have access"
    end
	end

  def update
    if current_user.update(user_params)
      flash[:success] = "User updated!"
      sign_in(current_user, :bypass => true)
      redirect_to user_path(current_user)
    else
      flash[:danger] = "User no update!"
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/views/users/_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar_top">
    <img src="https://i.pinimg.com/736x/b1/d3/a6/b1d3a6d64e26399b57e51b0bd77c6c19.jpg" alt="avatar" class="user_avatar" />
    <div class="info_wrap">
      <div class="user_name"><%= current_user&.username%></div>
      <button class="edit_info_btn">
        <img src="http://127.0.0.1:3000/assets/icons/ic_pencil.svg" alt="icon edit" class="icon_edit_info" />
        <span class="edit_info_text">
          <div class= "content_body_link1">
            <%= link_to t('.edit'), edit_user_path(current_user) %>
        </div>
        </span>
      </button>
    </div>
  </div>

  <ul class="sidebar_below">
    <li class="sidebar_menu_item">
      <img src="http://127.0.0.1:3000/assets/icons/ic_person.svg" alt="menu icon" class="sidebar_item_icon active_menu" />
      <span class="sidebar_item_text active_menu"><%= t('.name') %></span>
    </li>

    <div class="sidebar_sub_menu">
      <div class="sidebar_sub_item_text active_menu">
        <%= link_to t('.profile'), user_path(id: current_user.id) %>
      </div>
      <div class="sidebar_sub_item_text"><%= t('.bank') %></div>
      <div class="sidebar_sub_item_text">
        <div class= "content_body_link1">
          <%= link_to t('.address'), contact_path(current_user) %>
        </div>
      </div>
      <div class="sidebar_sub_item_text"><%= t('.change_password') %></div>
    </div>

    <li class="sidebar_menu_item">
      <img src="http://127.0.0.1:3000/assets/icons/ic_list.svg" alt="menu icon" class="sidebar_item_icon" />
      <span class="sidebar_item_text"><%= t('.purchase_order') %></span>
    </li>

    <li class="sidebar_menu_item">
      <img src="http://127.0.0.1:3000/assets/icons/ic_bell.svg" alt="menu icon" class="sidebar_item_icon" />
      <span class="sidebar_item_text"><%= t('.notify') %></span>
    </li>

    <li class="sidebar_menu_item">
      <img src="http://127.0.0.1:3000/assets/icons/ic_voucher.svg" alt="menu icon" class="sidebar_item_icon" />
      <span class="sidebar_item_text"><%= t('.voucher') %></span>
    </li>
  </ul>
</div>

app/views/users/edit.html.erb
<!-- BODY BLOCK -->
<main class="main_container">
  <%= render 'sidebar'%>
  <!-- Main Content -->
  <div class="main_content">
    <div class="main_content_head">
      <h3 class="content_head_title"><%= t('.my_profile') %></h3>
      <div class="content_head_desc"><%= t('.manage_profile') %></div>
    </div>

    <div class="main_content_body">
      <%= form_for current_user do |f| %>
        <form class="content_body_info">
          <div class="content_body_field">
            <div class="content_form_label"><%= t('.user_name') %></div>
            <div class="content_body_value">
              <%= f.text_field :username, class: "form-control" %>
            </div>
          </div>

          <div class="content_body_field">
            <div class="content_form_label"><%= t('.email') %></div>
            <div class="content_body_value">
              <%= f.email_field :email, class: "form-control" %>
            </div>
          </div>

          <div class="content_body_field">
            <div class="content_form_label"><%= t('.password') %></div>
            <div class="content_body_value">
              <%= f.password_field :password, class: "form-control" %>
            </div>
          </div>

          <div class="content_body_field">
            <div class="content_form_label"></div>
            <div class="content_body_value">
                <%= f.submit t('.submit'), class: "btn btn-primary" %>
            </div>
          </div>
        </form>
      <% end %>

      <div class="content_body_image">
        <div class="content_body_image_wrap">
          <img src="http://images6.fanpop.com/image/photos/36500000/Anime-image-anime-36567938-505-600.jpg" alt="edit_avatar" class="content_body_image_display" />
          <label for="image" class="content_body_image_btn">
            <input id="image" type="file" class="content_body_image_file" />
          </label>

          <div class="content_body_image_desc">
            <%= t('.usage') %> <br />
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

<!-- FOOTER BLOCK -->
<footer></footer>

app/views/users/show.html.erb
<!-- BODY BLOCK -->
<main class="main_container">
  <%= render 'sidebar'%>
  <!-- Main Content -->
  <div class="main_content">
    <div class="main_content_head">
      <h3 class="content_head_title"><%= t('.my_profile') %></h3>
      <div class="content_head_desc"><%= t('.manage_profile') %></div>
    </div>

    <div class="main_content_body">
      <form class="content_body_info">
        <div class="content_body_field">
          <div class="content_form_label"><%= t('.user_name') %></div>
          <div class="content_body_value"><%= current_user.username%></div>
        </div>

        <div class="content_body_field">
          <div class="content_form_label"><%= t('.email') %></div>
            <span class="content_body_value">
              <%= current_user.email%>
              <%= link_to "Thay Đổi", edit_user_path, class: 'content_body_link' %>
            </span>
          </div>
        </div>
      </form>

      <div class="content_body_image">
        <div class="content_body_image_wrap">
          <img src="https://i.pinimg.com/736x/b1/d3/a6/b1d3a6d64e26399b57e51b0bd77c6c19.jpg" alt="edit_avatar" class="content_body_image_display" />
          <label for="image" class="content_body_image_btn">
            <input id="image" type="file" class="content_body_image_file" />
          </label>

          <div class="content_body_image_desc">
            <%= t('.usage') %> <br />
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

<!-- FOOTER BLOCK -->
<footer></footer>