config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "static_pages#home"
    resources :users do
      get "cart", to: "carts#show"
    end
    resources :contacts
    resources :shops
    resources :products
    resources :line_items, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :user
	has_many :oders
  enum contact_type: { home: 0, company: 1 }
  default_scope -> { order(created_at: :desc) }
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :find_contact, only: [:edit, :update, :destroy]

	def new
		@contact = Contact.new
	end

  def show
    @contacts = current_user.contacts.order(created_at: :desc)
  end

	def create
    @contact = current_user.contacts.build(contacts_params)
    if @contact.save
      flash[:success] = t(".contact_created")
      redirect_to contact_path(current_user)
    else
      flash[:danger] = t(".contact_no_create")
      render :new
    end
  end

  def edit
    if @contact.present?
      unless @contact.user.id == current_user.id
        flash[:danger] = t(".access")
        redirect_to contact_path
      end
    else
      flash[:danger] = t(".find_contact")
      redirect_to root_path
    end
  end

  def update
    if @contact.update(contacts_params)
      flash[:success] = t(".contact_update")
      redirect_to contact_path(current_user)
    else
      flash[:danger] = t(".contact_fail_update")
      render :edit
    end
  end

  def destroy
    @contact.destroy
    flash[:success] = t(".contact_delete")
    redirect_to contact_path(current_user)
  end

	private

		def contacts_params
			params.require(:contact).permit(:contact_name, :phone, :address, :contact_type)
		end

    def find_contact
      @contact = Contact.find_by(id: params[:id])
      if @contact.nil?
        flash[:danger] = t(".contact_fail_find")
        redirect_to contact_path
      end
    end
end

app/views/contacts/_form_contact.html.erb
<div class="main_content_body">
  <%= form_for @contact do |f| %>
    <form class="content_body_info">
      <div class="content_body_field">
        <div class="content_body_value">
          <%= f.text_field :contact_name, class: "form-control", placeholder: t('.first_last_name') %>
        </div>
      </div>

      <div class="content_body_field">
        <div class="content_body_value">
          <%= f.text_field :phone, class: "form-control", placeholder: t('.phone') %>
        </div>
      </div>

      <div class="content_body_field">
        <div class="content_body_value">
          <%= f.text_field :address, class: "form-control", placeholder: t('.address') %>
        </div>
      </div>

      <div class="content_body_field">
        <div class="content_body_value">
          <div class ="content_body_value_text" ><%= t('.address_type') %></div>
          <%= f.select :contact_type, Contact.contact_types_i18n.invert %>
          <!--<%= f.select :contact_type, [t('.home'), t('.Company')]%>-->
        </div>
      </div>

      <div class="content_body_field">
        <div class="content_form_label_detail">
          <div class="content_form_label"></div>
          <div class="content_body_value">
            <%= f.submit t('.submit'), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </form>
  <% end %>
</div>

app/views/contacts/edit.html.erb
<main class="main_container">
  <%= render 'users/sidebar'%>    
  <div class="main_content">
    <div class="main_content_head">
      <h3 class="content_head_title"><%= t('.edit_address') %></h3>
    </div>
    <%= render 'form_contact'%>
  </div>
</main>

app/views/contacts/index.html.erb
<main class="main_container">
  <%= render 'users/sidebar'%>
  <div>
   <% @contacts.each do |contact| %>
    <%= contact.contact_name %>
    <%= contact.address %>
    <%= contact.phone %>
   <% end %> 
  </div>
</main>

app/views/contacts/new.html.erb
<main class="main_container">
  <%= render 'users/sidebar'%>
  <!-- Main Content -->
  <div class="main_content">
    <div class="main_content_head">
      <h3 class="content_head_title"><%= t('.new_address') %></h3>
    </div>

    <div class="main_content_body">
      <%= form_for @contact do |f| %>
        <form class="content_body_info">
          <div class="content_body_field">
            <div class="content_body_value">
              <%= f.text_field :contact_name, class: "form-control", placeholder: t('.first_last_name') %>
            </div>
          </div>

          <div class="content_body_field">
            <div class="content_body_value">
              <%= f.text_field :phone, class: "form-control", placeholder: t('.phone') %>
            </div>
          </div>

          <div class="content_body_field">
            <div class="content_body_value">
              <%= f.text_field :address, class: "form-control", placeholder: t('.address') %>
            </div>
          </div>

          <div class="content_body_field">
            <div class="content_body_value">
              <div class ="content_body_value_text" ><%= t('.address_type') %></div>
              <%= f.select :contact_type, Contact.contact_types_i18n.invert %>
              <!--<%= f.select :contact_type, [t('.home'), t('.Company')]%>-->
            </div>
          </div>

          <div class="content_body_field">
            <div class="content_form_label_detail">
              <div class="content_form_label"></div>
              <div class="content_body_value">
                <%= f.submit t('.submit'), class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        </form>
      <% end %>
    </div>
  </div>
</main>

app/views/contacts/show.html.erb
<main class="main_container">
  <%= render 'users/sidebar'%>    
  <div class="main_content">
    <div class="main_contacts_head">
      <div class="head_left">
        <div class="head_left_text"><%= t('.my_address') %></div>
      </div>
      <div class="head_right">
        <button class = "btn btn-danger">
          <div class="right_buttom">
            <div class="buttom_icon">
            </div>
            <div class="buttom_text">
              <%= link_to t('.my_address'), new_contact_path, class: 'contacts_body_link' %>
            <div>
          </div>
        </button>
      </div>
    </div>
    
    <div class="main_contacts_body">
      <% @contacts.each do |contact| %>
        <div class="contacts_body_field">
          <div class="contacts_body_label_left">
            <div class="contacts_body_label_value">
              <div class="contacts_body_label_value_left">
                <%= t('.first_last_name') %>
              </div>
              <div class="contacts_body_label_value_right">
                <div class ="contacts_body_label_value_right_text">
                  <%= contact.contact_name %>
              </div>
            </div>
          </div>
          <div class="contacts_body_label_right">
            <div class="contacts_body_label_right_text">
              <%= link_to t('.update'), edit_contact_path(contact.id), class: 'contacts_body_link1' %>
            </div>
            <div class="contacts_body_label_right_text1">
              <%= link_to t('.delete'), contact, method: :delete, data: { confirm: t('common.delete_confirm') } %>
            </div>
          </div>
        </div>

        <div class="contacts_body_field">
          <div class="contacts_body_label_left">
            <div class="contacts_body_label_value">
              <div class="contacts_body_label_value_left">
                <%= t('.phone') %>
              </div>
              <div class="contacts_body_label_value_right">
                <div class ="contacts_body_label_value_right_text">
                  <%= contact.phone %>
              </div>
            </div>
          </div>
        </div>

        <div class="contacts_body_field">
          <div class="contacts_body_label_left">
            <div class="contacts_body_label_value">
              <div class="contacts_body_label_value_left">
                <%= t('.address') %>
              </div>
              <div class="contacts_body_label_value_right">
                <div class ="contacts_body_label_value_right_text">
                  <%= contact.address %>
              </div>
            </div>
          </div>
        </div>
        <hr>
      <%end%>
    <div>

    
  </div>
</main>